### ISSUE TITLE
Accessible chatbot checklist

### ISSUE THREAD

**Issue by Doej0** [Doej0/greachybot#7]
- [ ] clear and concise language
- [ ] Keyboard accessibility
- [ ] high color contrast
- [ ] alternative text for images
- [ ] font resizing capabilities
- [ ] voice recognition/text-to-speech features
